---
Revisiting Central American and South American Tropics diversification: reviewing known diversification hypotheses, exploring patterns of coverage, and implications for future work
================
Annette Kang <sup>1*</sup> & Corrie S. Moreau <sup>1,2</sup>

<sup>1</sup> Department of Entomology, Cornell University, Ithaca, New York, USA

<sup>2</sup> Department of Ecology and Evolutionary Biology, Cornell University, Ithaca, New York, USA

  output: html
  github_document:
    toc: true
    toc_depth: 5
---

```{r setup, include=FALSE} knitr::opts_chunk$set(echo = TRUE)```

The American Tropics, more popularly referred to as the “Neotropics”, is the most biodiverse region in the world. For decades, scientists have introduced countless speciation hypotheses in an attempt to address how and why this region is so species rich. Despite these attempts, the origins and persistence of this biodiversity remain a mystery. In this review, we identify the main diversification modes at play and comprehensively revisit and explore these long-standing diversification hypotheses in the Central America and South American Tropics (CASA Tropics). Not only do we look at their origins and how they have progressed over the years, but we also offer additional perspective by compiling a large meta-analysis of over 2,000 publications, which we narrowed to almost 500 publications, to reveal underlying patterns in distribution and coverage across taxonomic groups, biogeographical regions, and drivers of diversification within the major hypotheses. In addition to revisiting our understanding of this biodiversity’s hotspots complex history, we also work towards an inclusive intention of changing the narrative surrounding the body of work that is done in this region and refer to the “Neotropics” as the CASA Tropics throughout this work to build on STEM’s efforts to work towards inclusive and non-colonizer language. Not only is it crucial to revisit our scientific understanding in this ultra-diverse region, but it is equally necessary for us to consider how we can shift the community’s language and research to be more inclusive.


# CASA Tropics Diversification Review Workflow
Brief explanation of meta-analysis steps and what documents to navigate to for more information.


- [Literature Pull from Clarivate's Web of Science](#literature-pull)
- [Broad Pattern Analysis](#broad-patterns)
- [Deeper Pattern Analysis](#deeper-patterns)


## Literature Pull from Clarivate's Web of Science

Using the Web of Science Database, we used multiple combinations of keyword searches to pull unique records of literature that pertinent to speciation and diversification in the CASA Tropics. 

***Unique Records are found on sheet "Unique Records Pull" in "Kang and Moreau_Supplementary References and Data.xlsx" in repository.***

We then sorted through this large compilation to make sure it satisfied our search parameters 

### TAXA
* Amphibians
* Insects
* Reptiles
* Mammals
* Birds
* Plants

### BIOGEOGRAPHIC REGIONS
* Amazonia
* Chaco
* North of IP
* Parana
* South of IP
* Tropical Andes

### DIVERSFICATION MODES
* Andes Uplift
* IP Emergence and CAS Closure
* Miocene Marine Incursions
* Pleistocene Climate
* Pleistocene Landscape
* Riverine Barrier
* Eastern South American Dry Diagonal

***Following sorting and categorizing, final literature used can be found on "Data Pull (Literature Analyzed)" sheet.***

## Broad Pattern Analysis

Count data was implemented on this final set of literature to gather number of diversification events associated with parameterized taxa, biogeographic regions, and diversification modes. 

***Data can be found on "Broad Analysis of Patterns" sheet.***

## Deeper Pattern Analysis

Further fine grain tests were run on gathered data such as ANOVA, Interactions between effects, contrasts between and among effects, and effect size. 

In order to run these fine grain tests on gathered data, we re-organized the final literature set. Navigate to "Kang_Literature Review_ANOVA.xlsx" for ANOVA organized data. 

***For full script on deeper pattern analysis, navigate to "Pattern Analysis.R" script in the repository.***